---
- name: This is to copy the alias conf file to httpd and restart using handler
  hosts: dev
  become: true
  gather_facts: true
  tasks:
    - name: ensure httpd is installed on target server
      ansible.builtin.yum:
        name: httpd
        state: present
   
    - name: ensure firewall port is enabled  
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
      notify: reload firewalld

    - name: copy alias conf file to the webserver and restart the serivce only if copy is succesful
      ansible.builtin.copy:
        src: alias.conf
        dest: /var/www/html/index.html
        force: yes
      notify: restart httpd service

  handlers:
    - name: reload firewalld
      ansible.builtin.command:
        cmd: firewall-cmd --reload

    - name: restart httpd service 
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: true
