---
- name: creating users without salt value, chars and digits
  hosts: dev
  become: true
  gather_facts: true
  vars_files:
    - user_list.yml
  tasks:
    - name: creating users
      vars:
        password: "{{ lookup('ansible.builtin.password', 'password-' + item.name ) }}"
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
        comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}"
      loop: "{{ users }}"
