---
- name: copy content from variable playbook
  hosts: servera.lab.example.com
  gather_facts: true
  become: true
  tasks:
    - name: create directory provided in extra variable
      ansible.builtin.file:
        path: "{{ DIRECTORY }}"
        state: directory
        mode: '0755'
    - name: copy content from variable  
      ansible.builtin.copy:
        content: "{{ CONTENT }}"
        dest: "{{ DIRECTORY }}/{{ FILE }}"
